<a href="https://colab.research.google.com/github/maryreginaf15/Programacao-Ia-Generativa/blob/main/PandasIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Conhecendo o Pandas

import pandas as pd

# 1. Criando um dicionario
dados_exemplo = {
    "Nome": ["Ana", "João", "Mariana"],
    "Idade": [25, 30, 22],
    "Profissão": ["Engenheira", "Médico", "Analista de Dados"]
}

#2. Transformando o dicionario em uma tabela (DataFrame)
df = pd.DataFrame(dados_exemplo)

print("Visualizando os dados organizados com o Pandas")
display(df)

#3. Separando apenas a coluna de Idades
idades = df["Idade"]
print("\nApenas a coluna de Idades")
display(idades)

Visualizando os dados organizados com o Pandas

      Nome  Idade          Profissão
0      Ana     25         Engenheira
1     João     30             Médico
2  Mariana     22  Analista de Dados

Apenas a coluna de Idades

0    25
1    30
2    22
Name: Idade, dtype: int64